### ISSUE TITLE
Uncaught ReferenceError: TencentCaptcha is not defined

### ISSUE THREAD

**Issue by wskkhn-hezhong** [leanflutter/flutter_tencent_captcha#2]
我 flutter clean  然后重新 flutter run  依然报错
I/X509Util(26347): Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
I/chromium(26347): [INFO:CONSOLE(47)] "Uncaught ReferenceError: TencentCaptcha is not defined", source: file:///android_asset/flutter_assets/packages/flutter_tencent_captcha/assets/captcha.html (47)

请问如何解决，谢谢了

**Comment by wskkhn-hezhong** [comment]
我用的是002

**Comment by wskkhn-hezhong** [comment]
OK了

**Comment by wskkhn-hezhong** [comment]
谢谢 003可以了

**Comment by lijy91** [comment]
请更新到 `0.0.3` 版本

**Comment by lijy91** [comment]
> 谢谢 003可以了

OK
