### ISSUE TITLE
Attempt to invoke interface method 'void org.leanflutter.plugins.flutter_tencent_captcha.TencentCaptchaListener.onLoaded(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by malikwang** [leanflutter/flutter_tencent_captcha#6]
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/26924433/194741734-469f696b-68b2-4c9f-aeb3-b3b204c4d3e4.png">

**Comment by lijy91** [comment]
Please update to 0.1.1
