### ISSUE TITLE
腾讯官方更新了插件地址，老的要失效了

### ISSUE THREAD

**Issue by Harveyzhao** [leanflutter/flutter_tencent_captcha#8]
![image](https://github.com/leanflutter/flutter_tencent_captcha/assets/15974393/81cd0215-66bd-4a65-8d02-a308dad975b8)
腾讯官方更新了地址，8月21号就老地址失效了，麻烦楼主大大更新下

**Comment by FantaZZ** [comment]
我也看到了，问下作者这个包更新了吗

**Comment by zdc939023** [comment]
不行就先拉到本地吧，修改后，本地依赖吧，这时间很快就到了。

**Comment by lijy91** [comment]
最近精力有限，欢迎大家提pr

**Comment by lijy91** [comment]
请更新到 [v0.1.2](https://github.com/leanflutter/flutter_tencent_captcha/releases/tag/v0.1.2)
